### ISSUE TITLE
LoadError: incompatible library version 

### ISSUE THREAD

**Issue by ssilverr** [HazAT/badge#102]
fastlane (2.162.0)

Any command involing add_badge fails,
including fastlane action add_badge with:

```
bundler: failed to load command: fastlane (/usr/local/Cellar/ruby@2.5/2.5.8/lib/bin/fastlane)
LoadError: incompatible library version - /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/curb-0.9.10/lib/curb_core.bundle
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/curb-0.9.10/lib/curl.rb:2:in `require'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/curb-0.9.10/lib/curl.rb:2:in `<top (required)>'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/curb-0.9.10/lib/curb.rb:2:in `require'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/curb-0.9.10/lib/curb.rb:2:in `<top (required)>'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/badge-0.12.0/lib/badge/runner.rb:4:in `require'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/badge-0.12.0/lib/badge/runner.rb:4:in `<top (required)>'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/badge-0.12.0/lib/badge.rb:2:in `require'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/badge-0.12.0/lib/badge.rb:2:in `<top (required)>'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-plugin-badge-1.4.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:5:in `require'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-plugin-badge-1.4.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:5:in `available_options'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-plugin-badge-1.4.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:22:in `available_options'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-plugin-badge-1.4.0/lib/fastlane/plugin/badge/actions/add_badge_action.rb:31:in `available_options'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane/lib/fastlane/documentation/actions_list.rb:133:in `print_options'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane/lib/fastlane/documentation/actions_list.rb:60:in `show_details'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane/lib/fastlane/documentation/actions_list.rb:6:in `run'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:246:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/bin/fastlane:23:in `load'
  /usr/local/Cellar/ruby@2.5/2.5.8/lib/bin/fastlane:23:in `<top (required)>'
```

**Comment by ssilverr** [comment]
So I've updated fastlane, installed rvm, used ruby 2.7 and now it works
