### ISSUE TITLE
Badge crashes at start 

### ISSUE THREAD

**Issue by keeferty** [HazAT/badge#11]
Crashes each time for me. Crash report number 7bf081fcf3dafd4e362e04059805b00f
```
/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:200:in `rescue in validate!': [!] ImageMagick/GraphicsMagick is not installed (MiniMagick::Invalid)
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:198:in `validate!'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:113:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:112:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:112:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:34:in `read'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:90:in `block in open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:89:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.1.1/lib/badge/runner.rb:78:in `add_badge'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.1.1/lib/badge/runner.rb:31:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.1.1/lib/badge/runner.rb:25:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.1.1/lib/badge/runner.rb:25:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.1.1/bin/badge:43:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.1.1/bin/badge:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.1.1/bin/badge:53:in `<top (required)>'
	from /usr/bin/badge:23:in `load'
	from /usr/bin/badge:23:in `<main>
```

**Comment by HazAT** [comment]
have you checked that you have imagemagick installed?
and if you run it in jenkins make sure this is in your PATH env variable
`PATH=$PATH:/usr/local/bin`

**Comment by keeferty** [comment]
Yup.
```
$ gem list image_magic

*** LOCAL GEMS ***

image_magick (0.1.9))
```

**Comment by HazAT** [comment]
http://stackoverflow.com/a/12253801

**Comment by keeferty** [comment]
Man i suck :P
Thanks, confirmed working
