### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by luvacu** [HazAT/badge#18]
Hi, I'm trying to use `badge` with `fastlane` (1.68.0) and I keep getting the same SSL error:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:98:in `block in load_shield'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:96:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:96:in `load_shield'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:29:in `block in run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:28:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/badge.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:36:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:162:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```
 Any thoughts on how to solve it? I'm running fastlane/badge on OS X Yosemite 10.10.5 with stock ruby 2.0 (`rvm` is not installed).

Thank you! 👏

**Comment by arunks** [comment]
Any update on this, I am also running into this same issue. 
Thanks!

**Comment by HazAT** [comment]
shield.io is not a very good service ... added failsafe and retry mechanisms to prevent errors.

Please update badge to 0.4.1 ... this version should fix all your errors.

**Comment by chezhong** [comment]
Still running to the same issue here. 
badge 0.4.2

[19:47:38]: Start adding badges...

Looking for related GitHub issues on fastlane/fastlane...


➡️  Error when upload ipa to testflight
   https://github.com/fastlane/fastlane/issues/2333 [closed] 5 💬
   07 Mar 2016

➡️  Intermittent SSL errors
   https://github.com/fastlane/fastlane/issues/2075 [closed] 35 💬
   18 Jun 2016

➡️  sslv3 alert handshake failure
   https://github.com/fastlane/fastlane/issues/395 [closed] 6 💬
   27 Jul 2015

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
