### ISSUE TITLE
bad URI(is not URI?)

### ISSUE THREAD

**Issue by tshtrifork** [HazAT/badge#28]
I'm getting the following error

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:176:in `split': [!] bad URI(is not URI?): https://img.shields.io/badge/3.9.0-726 (URI::InvalidURIError)
-green.png
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:33:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.2/lib/badge/runner.rb:114:in `block in load_shield'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.2/lib/badge/runner.rb:112:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.2/lib/badge/runner.rb:112:in `load_shield'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.2/lib/badge/runner.rb:31:in `block in run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.2/lib/badge/runner.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/actions/badge.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:89:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:239:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by HazAT** [comment]
Can you send me your command line call oder fastlane config?

**Comment by CRivlaldo** [comment]
In my case, I had the environment variables `http_proxy = XX.XX.XX.XX:XXXX` and `https_proxy = ...`
When I changed them to `http_proxy = http://XX.XX.XX.XX:XXXX` and `https_proxy = https://...` respectivle the issue has gone.
