### ISSUE TITLE
Running from fastlane is failing

### ISSUE THREAD

**Issue by beloso** [HazAT/badge#43]
I have installed `librsvg` with brew.
I am running badge from fastlane in jenkins and I keep getting this error.

```
+----------------------------+---------------------------------------------------------------------+
|                                           Lane Context                                           |
+----------------------------+---------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                 |
| PLATFORM_NAME                | ios                                                                 |
| LANE_NAME                         | ios dev                                                             |
| SCAN_DERIVED_DATA_PATH     | /Users/cashyt/jenkins/workspace/job/derivedData |
| SCAN_GENERATED_PLIST_FILES | []                                                                  |
| SCAN_GENERATED_PLIST_FILE  |                                                                     |
| BUILD_NUMBER               | 1013                                                                |
+----------------------------+---------------------------------------------------------------------+
[17:21:45]: no implicit conversion of nil into String
```

Not sure what I am mussing here

**Comment by wuaschtikus** [comment]
Same here.

**Comment by HazAT** [comment]
Can someone of you run it with `--verbose` to get more information about what's happening?
Thx

**Comment by wuaschtikus** [comment]
Seems there is an issue when executing these two lines in `runner.rb`.

```
 File.delete(shield) if File.exist?(shield)
 File.delete("#{shield.path}.png") if File.exist?("#{shield.path}.png")
```

There seems to be no `shield`to delete, or something like that.

**Comment by HazAT** [comment]
@wuaschtikus Thx ... just pushed an update ... please update to `0.8.3`
`gem update badge`

**Comment by wuaschtikus** [comment]
@HazAT Running with verbose gives nearly the same output. No further exceptions are logged...

**Comment by wuaschtikus** [comment]
Excellent.

**Comment by n3trino** [comment]
@HazAT  can you see the following exception when running badge from fastlane:

```
+-----------------------------+---------+
|             Lane Context              |
+-----------------------------+---------+
| DEFAULT_PLATFORM            | ios     |
| PLATFORM_NAME               | ios     |
| LANE_NAME                   | ios foo |
| GIT_REPO_WAS_CLEAN_ON_START | true    |
+-----------------------------+---------+
[13:53:33]: You don't have write permissions for the /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0 directory.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 💥   | badge                               | 19          |
| 5    | clean_build_artifacts               | 0           |
| 6    | reset_git_repo                      | 0           |
| 7    | notification                        | 0           |
| 8    | slack                               | 1           |
+------+-------------------------------------+-------------+

[13:53:33]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:692:in `verify_gem_home': [!] You don't have write permissions for the /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0 directory. (Gem::FilePermissionError)
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:811:in `pre_install_checks'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:278:in `install'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/resolver/specification.rb:97:in `install'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:166:in `block in install'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `each'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `install'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:250:in `install_gem'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/helper/gem_helper.rb:7:in `verify_gem!'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/badge.rb:5:in `run'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:94:in `block (2 levels) in parsing_binding'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /Users/stavrosschizas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/bin/fastlane:20:in `<top (required)>'
	from /Users/stavrosschizas/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/stavrosschizas/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by HazAT** [comment]
@n3trino I am not really sure that this is related to badge ...
Check this issue https://github.com/fastlane/fastlane/issues/1267
