### ISSUE TITLE
script doesn't finde fastlane installed with homebrew

### ISSUE THREAD

**Issue by cyrus86** [HazAT/badge#48]
no sure if and how I'm at fault, but even though fastlane is in my path, the script tries to find it through rubygems.
```
$ badge --shield "Version-0.0.3-blue" --dark --verbose    
/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'fastlane' (>= 2.0) among 140 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/xxx/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1428:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1410:in `activate'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /usr/local/bin/badge:22:in `<main>'
$ fastlane --version                                      
fastlane installation at path:
/Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.29.0/bin/fastlane
-----------------------------
fastlane 2.29.0
[app] echo $PATH                                              
/Users/xxx/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
```

**Comment by HazAT** [comment]
Strange I am not really sure what's going on here.
You could try fixing it by adding a Gemfile and run `bundle install` and see if this helps.

**Comment by HazAT** [comment]
Here is a shiny new comment.

**Comment by HazAT** [comment]
Here is a shiny new comment.

**Comment by HazAT** [comment]
I will close this now since this issue probably has nothing to do with this gem.
