### ISSUE TITLE
[!] Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by AnthonyMDev** [HazAT/badge#50]
Trying to use badge. Getting the following error:

````
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:229:in `mkdir': [!] Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0/curb-0.9.3 (Errno::EACCES)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:229:in `fu_mkdir'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:207:in `block (2 levels) in mkdir_p'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:205:in `reverse_each'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:205:in `block in mkdir_p'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:191:in `each'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/ext/builder.rb:213:in `write_gem_make_out'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/ext/builder.rb:135:in `build_error'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/ext/builder.rb:174:in `rescue in build_extension'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/ext/builder.rb:159:in `build_extension'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `each'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `build_extensions'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/installer.rb:752:in `build_extensions'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/installer.rb:304:in `install'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/resolver/specification.rb:97:in `install'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/request_set.rb:166:in `block in install'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `each'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `install'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/commands/install_command.rb:205:in `install_gem'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/helper/gem_helper.rb:7:in `verify_gem!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/actions/badge.rb:5:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:101:in `add_badge'
	from Fastfile:49:in `build_alpha'
	from Fastfile:252:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
````

**Comment by HazAT** [comment]
Looks like ruby is not allowed to create a folder. 
Maybe try this
https://github.com/bundler/bundler/issues/4590#issuecomment-220343182

**Comment by HazAT** [comment]
I will close this since this seems unrelated to this gem.
