### ISSUE TITLE
no decode delegate for this image format `APPICONSET'

### ISSUE THREAD

**Issue by olcayertas** [HazAT/badge#94]
Using this command:

`badge --dark --glob "/MyApp/Assets.xcassets/AppIconTest.appiconset"`

Getting this error:

```
[16:27:43]: Start adding badges...
[16:27:43]: './GozenPass/Assets.xcassets/AppIconTest.appiconset'

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	25: from /usr/local/bin/badge:23:in `<main>'
	24: from /usr/local/bin/badge:23:in `load'
	23: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/bin/badge:7:in `<top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/commands_generator.rb:11:in `start'
	21: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/commands_generator.rb:39:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/commands_generator.rb:34:in `block (2 levels) in run'
	14: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:65:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:65:in `each'
	12: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:76:in `block in run'
	11: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:189:in `add_badge'
	10: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:141:in `block in attribute'
	 9: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:17:in `[]'
	 8: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:44:in `cheap_info'
	 7: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:44:in `fetch'
	 6: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:45:in `block in cheap_info'
	 5: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:35:in `[]'
	 4: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:115:in `raw'
	 3: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:171:in `identify'
	 2: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/tool.rb:38:in `new'
	 1: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/tool.rb:90:in `call'
/Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/shell.rb:17:in `run': `identify -format %m %w %h %b ./GozenPass/Assets.xcassets/AppIconTest.appiconset[0]` failed with error: (MiniMagick::Error)
identify: no decode delegate for this image format `APPICONSET' @ error/constitute.c/ReadImage/562.
	25: from /usr/local/bin/badge:23:in `<main>'
	24: from /usr/local/bin/badge:23:in `load'
	23: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/bin/badge:7:in `<top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/commands_generator.rb:11:in `start'
	21: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/commands_generator.rb:39:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/commands_generator.rb:34:in `block (2 levels) in run'
	14: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:65:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:65:in `each'
	12: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:76:in `block in run'
	11: from /Library/Ruby/Gems/2.6.0/gems/badge-0.11.0/lib/badge/runner.rb:189:in `add_badge'
	10: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:141:in `block in attribute'
	 9: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:17:in `[]'
	 8: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:44:in `cheap_info'
	 7: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:44:in `fetch'
	 6: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:45:in `block in cheap_info'
	 5: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:35:in `[]'
	 4: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:115:in `raw'
	 3: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/image/info.rb:171:in `identify'
	 2: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/tool.rb:38:in `new'
	 1: from /Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/tool.rb:90:in `call'
/Library/Ruby/Gems/2.6.0/gems/mini_magick-4.9.5/lib/mini_magick/shell.rb:17:in `run': [!] `identify -format %m %w %h %b ./GozenPass/Assets.xcassets/AppIconTest.appiconset[0]` failed with error: (MiniMagick::Error)
identify: no decode delegate for this image format `APPICONSET' @ error/constitute.c/ReadImage/562.
```

**Comment by KeiroMidori** [comment]
Your command is incorrect it should be: `badge --dark --glob "/MyApp/Assets.xcassets/AppIconTest.appiconset/*.{png,PNG}"`

**Comment by HazAT** [comment]
Your `--glob` is pointing at the directory (`AppIconTest.appiconset`) rather than at files inside it. Use:

    badge --dark --glob "/MyApp/Assets.xcassets/AppIconTest.appiconset/*.{png,PNG}"

Also — as of v0.13.1 (#126) you usually don't need `--glob` at all. Badge now intelligently detects `.appiconset` directories via `Contents.json` and badges the right files automatically. Just run `badge` in your project root. Closing.
